const Map<String, String> ar = {
  // App
  'appName': 'ريستو',

  // Auth
  'login': 'تسجيل الدخول',
  'loggingIn': 'جاري تسجيل الدخول...',
  'register': 'إنشاء حساب',
  'registering': 'جاري إنشاء الحساب...',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'confirmPassword': 'تأكيد كلمة المرور',
  'name': 'الاسم',
  'phone': 'رقم الهاتف',
  'dontHaveAccount': 'ليس لديك حساب؟',
  'registerNow': 'سجل الآن',
  'alreadyHaveAccount': 'لديك حساب بالفعل؟',
  'loginNow': 'سجل دخولك الآن',
  'loginFailed': 'فشل تسجيل الدخول',
  'registerFailed': 'فشل إنشاء الحساب',
  'registerSuccess': 'تم إنشاء الحساب بنجاح!',
  'pleaseEnterEmail': 'يرجى إدخال البريد الإلكتروني',
  'pleaseEnterPassword': 'يرجى إدخال كلمة المرور',
  'pleaseEnterName': 'يرجى إدخال الاسم',
  'pleaseEnterPhone': 'يرجى إدخال رقم الهاتف',
  'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',

  // Navigation
  'home': 'الرئيسية',
  'cart': 'السلة',
  'myOrders': 'طلباتي',
  'profile': 'حسابي',

  // Home
  'hello': 'مرحباً، ',
  'search': 'بحث..',
  'all': 'الكل',
  'popularNow': 'الأكثر طلباً',
  'categories': 'الأقسام',
  'egp': 'ج.م',
  'spicy': 'حار',
  'unavailable': 'غير متوفر',

  // Product Details
  'description': 'الوصف',
  'ingredients': 'المكونات',
  'reviews': 'التقييمات',
  'addToCart': 'إضافة إلى السلة',
  'adding': 'جاري الإضافة...',
  'addedToCartSuccess': 'تمت الإضافة إلى السلة بنجاح!',
  'productIdMissing': 'معرف المنتج غير موجود',
  'postReview': 'نشر التقييم',
  'writeReview': 'اكتب تقييمك...',
  'yourRating': 'تقييمك',

  // Cart
  'myCart': 'سلتي',
  'clearCart': 'تفريغ السلة',
  'cartEmpty': 'سلتك فارغة',
  'cartEmptyDesc': 'استكشف قائمتنا اللذيذة وأضف وجباتك المفضلة إلى السلة!',
  'refreshCart': 'تحديث السلة',
  'total': 'الإجمالي',
  'items': 'عناصر',
  'item': 'عنصر',
  'checkout': 'إتمام الطلب',
  'orderSummary': 'ملخص الطلب',
  'order': 'الطلب',
  'taxes': 'الضرائب',
  'deliveryFees': 'رسوم التوصيل',
  'estimatedDeliveryTime': 'الوقت المتوقع للتوصيل:',
  'deliveryTimeValue': '15 - 30 دقيقة',
  'paymentMethods': 'طرق الدفع',
  'cashOnDelivery': 'الدفع عند الاستلام',
  'creditCard': 'بطاقة ائتمان / خصم مباشر',
  'payWithCard': 'الدفع بالبطاقة (Paymob)',
  'placeOrder': 'تأكيد الطلب',
  'placingOrder': 'جاري إرسال الطلب...',
  'orderPlacedSuccess': 'تم تقديم الطلب بنجاح!',
  'paymentCancelledOrFailed': 'تم إلغاء عملية الدفع أو فشلت',

  // Order History
  'orderHistory': 'سجل الطلبات',
  'orderHistorySubtitle': 'استعرض طلباتك السابقة وأعد طلب وجباتك المفضلة.',
  'allOrders': 'كل الطلبات',
  'ongoing': 'الحالية',
  'completed': 'المكتملة',
  'cancelled': 'الملغاة',
  'orderNumber': 'طلب رقم #',
  'noOrdersFound': 'لا توجد طلبات',
  'details': 'التفاصيل',
  'reorder': 'إعادة الطلب',
  'trackOrder': 'تتبع الطلب',
  'helpWithOrder': 'مساعدة بالطلب',
  'statusDelivered': 'تم التوصيل',
  'statusPending': 'قيد الانتظار',
  'statusPreparing': 'جاري التحضير',
  'statusOutForDelivery': 'في طريق التوصيل',
  'statusCancelled': 'ملغي',

  // Profile
  'account': 'الحساب',
  'preferences': 'التفضيلات',
  'support': 'الدعم والمساعدة',
  'favorites': 'المفضلة',
  'paymentMethodsMenu': 'طرق الدفع',
  'darkMode': 'الوضع الداكن',
  'lightMode': 'الوضع الفاتح',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',
  'selectLanguage': 'اختر اللغة',
  'helpCenter': 'مركز المساعدة',
  'about': 'عن التطبيق',
  'logout': 'تسجيل الخروج',
  'logoutConfirmTitle': 'تسجيل الخروج؟',
  'logoutConfirmMessage': 'هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'noAddressSet': 'لم يتم تحديد عنوان',

  // Common / Errors
  'error': 'خطأ',
  'retry': 'إعادة المحاولة',
  'tryAgain': 'حاول مجدداً',
  'loading': 'جاري التحميل...',
  'success': 'تم بنجاح',
};
