const Map<String, String> en = {
  // App
  'appName': 'Resto',

  // Auth
  'login': 'Login',
  'loggingIn': 'Logging in...',
  'register': 'Register',
  'registering': 'Registering...',
  'email': 'Email',
  'password': 'Password',
  'confirmPassword': 'Confirm Password',
  'name': 'Name',
  'phone': 'Phone',
  'dontHaveAccount': "Don't have an account?",
  'registerNow': 'Register Now',
  'alreadyHaveAccount': 'Already have an account?',
  'loginNow': 'Login Now',
  'loginFailed': 'Login failed',
  'registerFailed': 'Registration failed',
  'registerSuccess': 'Account created successfully!',
  'pleaseEnterEmail': 'Please enter your email',
  'pleaseEnterPassword': 'Please enter your password',
  'pleaseEnterName': 'Please enter your name',
  'pleaseEnterPhone': 'Please enter your phone number',
  'passwordsDoNotMatch': 'Passwords do not match',

  // Navigation
  'home': 'Home',
  'cart': 'Cart',
  'myOrders': 'My Orders',
  'profile': 'Profile',

  // Home
  'hello': 'Hello, ',
  'search': 'Search..',
  'all': 'All',
  'popularNow': 'Popular Now',
  'categories': 'Categories',
  'egp': 'EGP',
  'spicy': 'Spicy',
  'unavailable': 'Unavailable',

  // Product Details
  'description': 'Description',
  'ingredients': 'Ingredients',
  'reviews': 'Reviews',
  'addToCart': 'Add to Cart',
  'adding': 'Adding...',
  'addedToCartSuccess': 'added to cart successfully!',
  'productIdMissing': 'Product ID is missing',
  'postReview': 'Post Review',
  'writeReview': 'Write a review...',
  'yourRating': 'Your Rating',

  // Cart
  'myCart': 'My Cart',
  'clearCart': 'Clear Cart',
  'cartEmpty': 'Your Cart is Empty',
  'cartEmptyDesc': 'Explore our delicious menu and add food to your cart!',
  'refreshCart': 'Refresh Cart',
  'total': 'Total',
  'items': 'items',
  'item': 'item',
  'checkout': 'Checkout',
  'orderSummary': 'Order summary',
  'order': 'Order',
  'taxes': 'Taxes',
  'deliveryFees': 'Delivery fees',
  'estimatedDeliveryTime': 'Estimated delivery time:',
  'deliveryTimeValue': '15 - 30 mins',
  'paymentMethods': 'Payment Methods',
  'cashOnDelivery': 'Cash on Delivery',
  'creditCard': 'Credit Card / Debit Card',
  'payWithCard': 'Pay with Card (Paymob)',
  'placeOrder': 'Place Order',
  'placingOrder': 'Placing Order...',
  'orderPlacedSuccess': 'Order placed successfully!',
  'paymentCancelledOrFailed': 'Payment was cancelled or failed',

  // Order History
  'orderHistory': 'Order History',
  'orderHistorySubtitle': 'Review your past cravings and reorder your favorites.',
  'allOrders': 'All Orders',
  'ongoing': 'Ongoing',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'orderNumber': 'Order #',
  'noOrdersFound': 'No orders found',
  'details': 'Details',
  'reorder': 'Reorder',
  'trackOrder': 'Track Order',
  'helpWithOrder': 'Help with Order',
  'statusDelivered': 'DELIVERED',
  'statusPending': 'PENDING',
  'statusPreparing': 'PREPARING',
  'statusOutForDelivery': 'OUT FOR DELIVERY',
  'statusCancelled': 'CANCELLED',

  // Profile
  'account': 'ACCOUNT',
  'preferences': 'PREFERENCES',
  'support': 'SUPPORT',
  'favorites': 'Favorites',
  'paymentMethodsMenu': 'Payment Methods',
  'darkMode': 'Dark Mode',
  'lightMode': 'Light Mode',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'selectLanguage': 'Select Language',
  'helpCenter': 'Help Center',
  'about': 'About',
  'logout': 'Log out',
  'logoutConfirmTitle': 'Log out?',
  'logoutConfirmMessage': 'Are you sure you want to log out of your account?',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'noAddressSet': 'No address set',

  // Common / Errors
  'error': 'Error',
  'retry': 'Retry',
  'tryAgain': 'Try Again',
  'loading': 'Loading...',
  'success': 'Success',
};
